### ISSUE TITLE
Issues with jimp 6.14.8 , worked with jimp@0.6.3

### ISSUE THREAD

**Issue by Nartek01** [jimp-dev/jimp#976]
# Expected Behavior

Change the resolution of the image "image.jpeg" to 300px x 200px

# Current Behavior

Got error that jimp cannot be found inside node_modules

## Steps to Reproduce

``` paste this code inside **index.js**
let Jimp = require("jimp")

Jimp.read("image.jpeg", (err, image) => {
    if (err) throw err
    image
        .resize(300, 200)
        .write("image-modified.jpeg")
})
```

IF YOUR ISSUE DEPENDS ON A PARTICULAR IMAGE BE SURE TO INCLUDE THIS AS WELL. WE CAN'T REPORDUCE IF WE DON'T HAVE YOUR IMAGE

1. step create folder and paste two images with different resolution
2. step create a file "index.js" and paste above mentioned code inside
3. step inside choosen terminal navigate to folde where the images and index.js file is and type $node index.js

**Screenshots**

## Context

- Jimp Version: 6.14.8
- Operating System: 10.0.19242 Build 19042
- Node version: 14.15.0

## Failure Logs
$ node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module './jimp'
Require stack:
- C:\Users\Nara\Dropbox\Skola ITHS\Avancera\NodeJS\Bildbehandling\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m     
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Nara\Dropbox\Skola ITHS\Avancera\NodeJS\Bildbehandling\index.js:1:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m       
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Nara\\Dropbox\\Skola ITHS\\Avancera\\NodeJS\\Bildbehandling\\index.js'←[39m
  ]
}

**Comment by Nartek01** [comment]
Hello to clarify I tried let Jimp = require("jimp") , ("./node_modules/jimp") (./node_modules/@jimp)  and (" /jimp ")

**Comment by hipstersmoothie** [comment]
jimp does not have a version that high
