### ISSUE TITLE
Jimp 0.22.7 read function undefined

### ISSUE THREAD

**Issue by djaffer** [jimp-dev/jimp#1211]
# Expected Behavior

jimp.read is no longer working after upgrading to 0.22.7
# Current Behavior

jimp.read is failing with error that there is not a fuction

# Failure Information (for bugs)

typeError: jimp__WEBPACK_IMPORTED_MODULE_13___default.a.read is not a function
    at _callee5$ (index.js:452:1)
    at tryCatch (vendors~main.chunk.js:1302:17)
    at Generator.<anonymous> (vendors~main.chunk.js:1383:22)
    at Generator.next (vendors~main.chunk.js:1327:21)
    at asyncGeneratorStep (vendors~main.chunk.js:635:24)
    at _next (vendors~main.chunk.js:654:9)
    at vendors~main.chunk.js:659:7
    at new Promise (<anonymous>)
    at vendors~main.chunk.js:651:12
    at addVirtualBackground (index.js:440:1)
    at index.js:132:1
    at invokePassiveEffectCreate (vendors~main.chunk.js:477276:24)
    at HTMLUnknownElement.callCallback (vendors~main.chunk.js:460574:18)
    at Object.invokeGuardedCallbackDev (vendors~main.chunk.js:460618:20)
    at invokeGuardedCallback (vendors~main.chunk.js:460673:35)
    at flushPassiveEffectsImpl (vendors~main.chunk.js:477346:13)
    at unstable_runWithPriority (vendors~main.chunk.js:480393:16)
    at runWithPriority$1 (vendors~main.chunk.js:466910:14)
    at flushPassiveEffects (vendors~main.chunk.js:477242:18)
    at vendors~main.chunk.js:477140:15
    at workLoop (vendors~main.chunk.js:480353:38)
    at flushWork (vendors~main.chunk.js:480331:18)
    at MessagePort.performWorkUntilDeadline (vendors~main.chunk.js:480129:31)
## Steps to Reproduce
```
import jimp from 'jimp';

const jimpImage = await jimp.read(imgSrc);
```

**Screenshots**

## Context

- Jimp Version: 0.22.7
- Webpack: 4.44.2 
- Node version: 18.14.2

## Failure Logs
ypeError: jimp__WEBPACK_IMPORTED_MODULE_13___default.a.read is not a function
    at _callee5$ (index.js:452:1)
    at tryCatch (vendors~main.chunk.js:1302:17)
    at Generator.<anonymous> (vendors~main.chunk.js:1383:22)
    at Generator.next (vendors~main.chunk.js:1327:21)
    at asyncGeneratorStep (vendors~main.chunk.js:635:24)
    at _next (vendors~main.chunk.js:654:9)
    at vendors~main.chunk.js:659:7
    at new Promise (<anonymous>)
    at vendors~main.chunk.js:651:12
    at addVirtualBackground (index.js:440:1)
    at index.js:132:1
    at invokePassiveEffectCreate (vendors~main.chunk.js:477276:24)
    at HTMLUnknownElement.callCallback (vendors~main.chunk.js:460574:18)
    at Object.invokeGuardedCallbackDev (vendors~main.chunk.js:460618:20)
    at invokeGuardedCallback (vendors~main.chunk.js:460673:35)
    at flushPassiveEffectsImpl (vendors~main.chunk.js:477346:13)
    at unstable_runWithPriority (vendors~main.chunk.js:480393:16)
    at runWithPriority$1 (vendors~main.chunk.js:466910:14)
    at flushPassiveEffects (vendors~main.chunk.js:477242:18)
    at vendors~main.chunk.js:477140:15
    at workLoop (vendors~main.chunk.js:480353:38)
    at flushWork (vendors~main.chunk.js:480331:18)
    at MessagePort.performWorkUntilDeadline (vendors~main.chunk.js:480129:31)

**Comment by djaffer** [comment]
Looks import statement is modified to "jimp/es". This should be clearly added in change log.
