### ISSUE TITLE
Can't find 'resize/ method anymore

### ISSUE THREAD

**Issue by bobzel** [jimp-dev/jimp#1304]
# Expected Behavior

I expect  this code to work:

import { Jimp, ResizeStrategy } from 'jimp';
...
const img = await Jimp.read(sourcepath);
img.resize(500, ResizeStrategy.AUTO)

# Current Behavior

Property 'resize' does not exist on type '{ bitmap: Bitmap; background: number; formats: Format<any, undefined>[]; inspect(): string; toString(): string; getBuffer<ProvidedMimeType_2 extends string, Options_3 extends Record<string, undefined> extends Record<...> ? O : never>(mime: ProvidedMimeType_2, options?: Options_3 | undefined): Promise<...>; ... 9 mor...'.

# Failure Information (for bugs)

## Steps to Reproduce

this is a compile time problem

## Context

This proble began after upgrading to v1.02

**Comment by hipstersmoothie** [comment]
can you provide a reproduction?

**Comment by bobzel** [comment]
The Jimp index.js source file appears to have removed all functionality other than circle methods.  If I comment them back in, things compile.  I'm assuming this is an oversight since the documentation doesnt say that I would need to call createJimp with all of this stuff.

starting at line 123 of index.js:

exports.Jimp = (0, core_1.createJimp)({
    // formats: [bmp, msBmp, gif, jpeg, png, tiff],
    plugins: [
        // blit.methods,
        // blur.methods,
        circle.methods,
        // color.methods,
        // contain.methods,
        // cover.methods,
        // crop.methods,
        // displace.methods,
        // dither.methods,
        // fisheye.methods,
        // flip.methods,
        // hash.methods,
        // mask.methods,
        // print.methods,
        // resize.methods,
        // rotate.methods,
        // threshold.methods,
    ],
});

**Comment by hipstersmoothie** [comment]
Ah I've been publishing locally and forgot to build 😓 Next release should fix

**Comment by bobzel** [comment]
for clarity, this is what I need to do instead of simply importing Jimp.  I don't know whether ResizeStrategy.AUTO is now the default since it seems to have gone away, or whether I need to do something else to specify it.


import * as core_1 from '@jimp/core';
import jpeg from '@jimp/js-jpeg';
import png from '@jimp/js-png';
import bmp, { msBmp } from '@jimp/js-bmp';
import gif from '@jimp/js-gif';
import tiff from '@jimp/js-tiff';
import * as resize from '@jimp/plugin-resize';
const Jimp = core_1.createJimp({
    formats: [jpeg, png, bmp, gif, tiff],
    plugins: [resize.methods],
});

...
Jimp.read(pathname).then(img => img.resize({ w: width }))

**Comment by hipstersmoothie** [comment]
Okay I think 1.0.4 should fix this for you

**Comment by hipstersmoothie** [comment]
As for the `AUTO` constant it is not longer needed with the new API. It was only ever there as a placeholder for the arguments. I'm preparing the docs still

**Comment by bobzel** [comment]
great, thank you!

**Comment by hipstersmoothie** [comment]
If it works could you close the issue?

**Comment by daliusd** [comment]
1.0.4 has not fixed this problem.

**Comment by bobzel** [comment]
1.04 fixed the issue for me

**Comment by archasek** [comment]
Where's docs for jimp ?

**Comment by hipstersmoothie** [comment]
Docs are deployed now http://jimp-dev.github.io/jimp

If they lack feel free to opens issues/PRs!
